services:
  # Service PostgreSQL
  database:
    container_name: mgmt-db
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-_ChangeMe_}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-d",
          "${POSTGRES_DB:-app}",
          "-U",
          "${POSTGRES_USER:-app}",
        ]
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data:rw
    networks:
      - app-network

  # Service PHP-FPM avec les extensions demandées
  php:
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    container_name: mgmt-php
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    networks:
      - app-network

  # Service NGINX
  nginx:
    image: nginx:latest
    container_name: mgmt-nginx
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
