FROM jakzal/phpqa:php8.3
RUN apt-get update && \
    apt-get install -y libldap2-dev libsodium-dev libpq-dev && \
    docker-php-ext-install ldap intl bz2 zip sodium bcmath pcntl pdo_pgsql pgsql
RUN pecl install xdebug-3.3.2 && \
    echo 'zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20230831/xdebug.so' > /usr/local/etc/php/conf.d/docker-php-xdebug.ini && \
    echo 'xdebug.mode=develop,coverage' >> /usr/local/etc/php/conf.d/docker-php-xdebug.ini && \
    echo 'xdebug.start_with_request = yes' >> /usr/local/etc/php/conf.d/docker-php-xdebug.ini