<?php

namespace App\DataFixtures;

use App\Entity\App;
use App\Entity\AppUpdateType;
use App\Entity\Setting;
use App\Entity\Log;
use App\Entity\Server;
use App\Entity\ServerType;
use App\Entity\User;
use DateTime;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Bundle\FixturesBundle\FixtureGroupInterface;
use Doctrine\Persistence\ObjectManager;

class DevFixtures extends Fixture implements FixtureGroupInterface
{
    public function load(ObjectManager $manager): void
    {
        $testUser = new User();
        $testUser->setLogin('Test user');
        $testUser->setLastLogin(new DateTime());
        $testUser->setActive(true);
        $manager->persist($testUser);
        $lastMonth = new DateTime();
        $lastMonth->modify('-1 month');
        $threeMonth = new DateTime();
        $threeMonth->modify('-3 months');
        $noRule = new AppUpdateType();
        $noRule->setName('');
        $manager->persist($noRule);
        $githubRelease = new AppUpdateType();
        $githubRelease->setName('GitHub Release');
        $manager->persist($githubRelease);
        $githubTag = new AppUpdateType();
        $githubTag->setName('GitHub Tag');
        $manager->persist($githubTag);
        $debian = new AppUpdateType();
        $debian->setName('Debian');
        $manager->persist($debian);
        $docker = new AppUpdateType();
        $docker->setName('Docker');
        $manager->persist($docker);
        $crawler = new AppUpdateType();
        $crawler->setName('Crawler');
        $manager->persist($crawler);
        $appGlpi = new App();
        $appGlpi->setName('GLPI');
        $appGlpi->setCurrentVersion('9.0');
        $appGlpi->setLastUpdate($threeMonth);
        $appGlpi->setUpdateType($githubRelease);
        $appGlpi->setUpdateResource('glpi-project/glpi');
        $appGlpi->setDocumentation('https://www.google.fr');
        $manager->persist($appGlpi);
        $appSympa = new App();
        $appSympa->setName('Sympa');
        $appSympa->setCurrentVersion('2.0');
        $appSympa->setLastUpdate($threeMonth);
        $appSympa->setUpdateType($debian);
        $appSympa->setUpdateResource('sympa');
        $manager->persist($appSympa);
        $appNextCloud = new App();
        $appNextCloud->setName('NextCloud');
        $appNextCloud->setCurrentVersion('2.0');
        $appNextCloud->setLastUpdate($threeMonth);
        $appNextCloud->setUpdateType($noRule);
        $manager->persist($appNextCloud);
        $appGlpi2 = new App();
        $appGlpi2->setName('GLPI');
        $appGlpi2->setCurrentVersion('9.5');
        $appGlpi2->setLastUpdate($lastMonth);
        $appGlpi2->setUpdateType($githubRelease);
        $appGlpi2->setUpdateResource('glpi-project/glpi');
        $manager->persist($appGlpi2);
        $debian12 = new ServerType();
        $debian12->setLabel('Debian 12');
        $manager->persist($debian12);
        $windowsServer = new ServerType();
        $windowsServer->setLabel('Windows Server');
        $manager->persist($windowsServer);
        $oracle = new ServerType();
        $oracle->setLabel('Oracle');
        $manager->persist($oracle);
        $server0 = new Server();
        $server0->setName('GLPI');
        $server0->setIp('192.168.3.254');
        $server0->setLastUpdate(new DateTime());
        $server0->setType($debian12);
        $server0->addApp($appGlpi);
        $manager->persist($server0);
        $server1 = new Server();
        $server1->setName('GW');
        $server1->setIp('192.168.1.254');
        $server1->setLastUpdate(new DateTime());
        $server1->setType($debian12);
        $server1->setDocumentation('https://www.yahoo.fr');
        $manager->persist($server1);
        $server2 = new Server();
        $server2->setName('DNS');
        $server2->setIp('192.168.1.200');
        $server2->setLastUpdate($lastMonth);
        $server2->setType($windowsServer);
        $manager->persist($server2);
        $server3 = new Server();
        $server3->setName('Web');
        $server3->setType($debian12);
        $server3->addApp($appGlpi2);
        $server3->addApp($appNextCloud);
        $manager->persist($server3);
        $twoWeeks = new DateTime();
        $twoWeeks->modify('-2 weeks');
        $server4 = new Server();
        $server4->setName('DB1');
        $server4->setType($debian12);
        $server4->setLastUpdate($twoWeeks);
        $manager->persist($server4);
        $threeWeeks = new DateTime();
        $threeWeeks->modify('-3 weeks');
        $server5 = new Server();
        $server5->setName('DB2');
        $server5->setIp('192.168.3.254');
        $server5->setType($oracle);
        $server5->setLastUpdate($threeWeeks);
        $manager->persist($server5);
        $log1 = new Log();
        $log1->setDate(new DateTime());
        $log1->setMessage('Mise à jour');
        $log1->setServer($server1);
        $log1->setUsername($testUser->getLogin());
        $manager->persist($log1);
        $log2 = new Log();
        $log2->setDate($lastMonth);
        $log2->setMessage('Mise à jour');
        $log2->setServer($server2);
        $log2->setUsername($testUser->getLogin());
        $manager->persist($log2);
        $serverA = new Server();
        $serverA->setName('Web ext');
        $serverA->setIp('192.168.9.254');
        $serverA->setLastUpdate(new DateTime());
        $serverA->setType($debian12);
        $serverA->addApp($appSympa);
        $manager->persist($serverA);
        $configWarningLimit = new Setting();
        $configWarningLimit->setName('warning_threshold');
        $configWarningLimit->setValue('10');
        $manager->persist($configWarningLimit);
        $configErrorLimit = new Setting();
        $configErrorLimit->setName('alert_threshold');
        $configErrorLimit->setValue('30');
        $manager->persist($configErrorLimit);
        $manager->flush();
    }

    public static function getGroups(): array
    {
        return ['dev'];
    }
}
